### ISSUE TITLE
More settings options

### ISSUE THREAD

**Issue by TparT** [AllPoland/ArcViewer#19]
Ability to mute the Hit Sound

Ability to see basic map information, like:
- Notes Per Second (NPS)
- Total amount of notes
- BPM
- Bombs
- Walls
- Lighting events

Ability to open (Like pressing a button or copying the link of) the previewed map on map searching websites like:
- BeatSaver
- BeastSaber

**Comment by AllPoland** [comment]
> Ability to mute the Hit Sound
This already exists in the form of "Hit Sound Volume". Just set it to 0

> Ability to see basic map information
I've considered this before, but I don't see any use from it that would warrant the effort to add a stats screen. Multiple people have asked for it though, so it *might* be added in the future.

> Ability to open the previewed map on a map download site
I'll definitely add this one to the list, although it will only link to BeatSaver, since BeastSaber is undergoing a rewrite and won't be a place for downloading maps soon.

**Comment by AntonBogun** [comment]
It would also be nice to have an option that removes arrows and shows what the map looks like with the "no arrows" modifier enabled.

**Comment by ccloli** [comment]
> Ability to see basic map information

I second this, I usually preview the map before I download it, so that I can determine if I could play the map (like too fast or too tech?). By checking its information like NPS I can have a quick view of the level, like if it exceeds my acceptable NPS I can directly switch to another difficulty.

Though I wrote a script just now, that runs on BeatSaver to show the information from BeatSaver API, I still sometimes forget to check it before I preview the map, or I may just forget which level I need to check after I open the preview modal. Besides, the API only returns the average NPS, while the Rabbit one can show the peak NPS, which may be suitable for some maps with uneven density of blocks like [this one](https://beatsaver.com/maps/3282c), though a better way should be like showing 90th NPS or 95th NPS in map information.

![image](https://github.com/AllPoland/ArcViewer/assets/8115912/1814249b-0249-413d-b9a9-86e429304bb1)

**Comment by AllPoland** [comment]
Both the stats panel (including counters for all objects, NPS, and SPS), and buttons linking to BeatSaver page/map download have been added in v0.3.5
