### ISSUE TITLE
Any reason for not supporting Gameplay?

### ISSUE THREAD

**Issue by mathieucaroff** [AllPoland/ArcViewer#31]
The Readme tells about Gameplay that:

> These features aren't included, and most likely never will be. If you ask for these I will unceremoniously tell you no.

I'm wondering why not support it? As a Quest user, since the last few updates, I've not been able to mod the game. Furthermore, I'm quite bored of having to patch it over and over. I'm considering forking to add the Gameplay, which should be fairly easy in comparison with the work it must have taken to create the viewer.

Anyway, if there's any reason not to  support it I should consider, if you feel like writing about it, I'd be glad to know about them.

Thank you for the great software!

**Comment by AllPoland** [comment]
Legal reasons. ArcViewer is a full reconstruction of game logic, systems, and visuals. The reason this works out ok is specifically because it's not playable. Adding gameplay to ArcViewer would be creating a video game that's entirely identical to Beat Saber, in terms of design and logic, which is definitely not legal.

I would heavily advise against forking ArcViewer and adding gameplay.
