### ISSUE TITLE
[ Suggestion ] Ability to not have to refresh each time you replace a note in a WIP while watching a map

### ISSUE THREAD

**Issue by Specture7** [AllPoland/ArcViewer#5]
If possible, it would be cool to be able to not have to like refresh the file every time you place a note. So like if you could instead of create a ZIP for every time you place a note, maybe be able to just click on the folder that's not the ZIP but the map whole map folder. Like before you click create ZIP. Would be cool if possible.

**Comment by AllPoland** [comment]
I assume you mean hot reload the map, which already exists on the desktop version, as well as loading from unzipped directories. These things aren't possible on the web version, which is why they aren't there.

If you download the desktop version, you can load an unzipped map by navigating to one of the .dat files, and there'll be a quick reload button which will refresh the map in real time.

**Comment by Specture7** [comment]
I have the desktop version, I didn't know that exists. Thank you this will make everything so much easier.
