### ISSUE TITLE
[Feature Request] Better mobile browser support

### ISSUE THREAD

**Issue by f1amy** [AllPoland/ArcViewer#68]
I occasionally use my phone and tablet to watch BeatLeader replays.
ArcViewer already sort of works if you open it in mobile browser like Chrome or Safari. The issue is that it is not really optimized for this use case and I can't comfortably use it.

Problems:
1. On the menu screen I cannot invoke a keyboard to enter/paste a link or replay ID.
2. The UI is too big for a mobile device, elements of the UI overlap with each other.

It would be really nice if some of the problems could be resolved.

Thanks!

![Screenshot_20240725-222003](https://github.com/user-attachments/assets/57c592c1-2ef7-4b6a-bd6a-5d9c87fa175e)

**Comment by AllPoland** [comment]
Unfortunately ArcViewer was never made to work on mobile. I probably could make this more clear in the readme, but the fact that it works at all on mobile browsers is more of a coincidence than any effort on my part.

For issue 1, this is not a simple issue at all to fix, and it's one that I don't have any current plans on addressing. This does unfortunately mean that you can only open maps on mobile by going through shareable links, but again - the fact that mobile works at all isn't because I actively support it.

For issue 2, this is mostly solved by using the screen horizontally. You can additionally change the UI scale in the settings if you need to. ArcViewer's UI just wasn't designed to handle such a tall aspect ratio.

**Comment by f1amy** [comment]
I understand, thanks for reply!
